simplemooc/simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from simplemooc.accounts.views import registerPageView, dashboardPageView, editPageView, editPasswordPageView, passwordResetPageView, passwordResetConfirmPageView

urlpatterns = [
    path('', dashboardPageView, name='dashboard'),
    path('entrar/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('sair/', LogoutView.as_view(next_page = 'accounts:login'), name='logout'),
    path('cadastrar/', registerPageView, name='register'),
    path('esqueceu_senha/', passwordResetPageView, name='password_reset'),
    path('alterar_senha/<str:key>', passwordResetConfirmPageView, name='password_reset_confirm'),
    path('editar/', editPageView, name='edit'),
    path('editar_senha/', editPasswordPageView, name='edit_password'),
]

simplemooc/simplemooc/core/urls.py
from django.urls import path
from simplemooc.core.views import homePageView, contactPageView

urlpatterns = [
    path('', homePageView, name='home'),
    path('contato/', contactPageView, name='contact'),
]

simplemooc/simplemooc/courses/urls.py
from django.urls import path
from simplemooc.courses.views import coursePageView, detailsPageView, enrollmentPageView

urlpatterns = [
    path('', coursePageView, name='index'),
    path('<slug:slug>/', detailsPageView, name='details'),
    path('<slug:slug>/inscricao/', enrollmentPageView, name='enrollment'),
]

simplemooc/simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('simplemooc.core.urls', 'core'), namespace='core')),
    path('cursos/', include(('simplemooc.courses.urls', 'courses'), namespace='courses')),
    path('conta/', include(('simplemooc.accounts.urls', 'accounts'), namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/simplemooc/core/views.py
from django.shortcuts import render

# Create your views here.

def homePageView(request):
    return render(request, 'home.html', {'usuario': 'Marcos'})

def contactPageView(request):
    return render(request, 'contact.html')

simplemooc/simplemooc/core/templates/Partials/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a responsive product landing page.">
    <title>Simple MOOC Layout - Pure CSS</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Semantic-UI/semantic.min.css' %}">
  </head>
  <body>
    <div class="ui inverted grey labeled icon left sidebar segment">
      <div class="ui secondary vertical menu">
        <div class="ui animated list">
          <div class="item">
            <a class="item" href="{% url 'core:home' %}"><i class="inverted large home icon"></i><h3 class='ui grey inverted header'>Início</h3></a>
          </div>
          <div class="item">
            <a class="item" href="{% url 'courses:index' %}"><i class="inverted large book icon"></i><h3 class='ui grey inverted header'>Cursos</h3></a>
          </div>
          <div class="item">
            <a class="item"><i class="inverted large comments icon"></i><h3 class='ui grey inverted header'>Fórum</h3></a>
          </div>
          <div class="item">
            <a class="item" href="{% url 'core:contact' %}"><i class="inverted large address card icon"></i><h3 class='ui grey inverted header'>Contato</h3></a>
          </div>
          {% if user.is_authenticated %}
          <div class="item">
            <a class="item" href="{% url 'accounts:dashboard' %}"><i class="inverted large chart bar icon"></i><h3 class='ui grey inverted header'>Dashboard</h3></a>
          </div>
          <div class="item">
            <a class="item" href="{% url 'accounts:logout' %}"><i class="inverted large sign-in icon"></i><h3 class='ui grey inverted header'>Sair</h3></a>
          </div>
          {% else %}
          <div class="item">
            <a class="item" href="{% url 'accounts:login' %}"><i class="inverted large sign-in icon"></i><h3 class='ui grey inverted header'>Entrar</h3></a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    
    <div class="ui inverted grey fixed one item compact menu huge">
      <div class="ui center aligned container segment inverted grey">
          <a class="item toggler"><i class="sidebar icon"></i>SIMPLE MOOC</a>
      </div>
    </div>
    
    <div class="ui segments">
      <br>
      
      {% block content %} {% endblock %}

      <div class="ui center aligned inverted segment grey very padded">
        <h5>Copyright © 2018/2022 - Wesley Mendes | Simple MOOC - Uma simples plataforma de ensino a distância</h5>
      </div>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous">
    </script>
    <script src="{% static 'js/style.js' %}"></script>
    <script src="{% static 'Semantic-UI/semantic.min.js' %}"></script>
  </body>
</html>