simplemooc/simplemooc/core/urls.py
from django.urls import path
from simplemooc.core.views import homePageView, contactPageView

urlpatterns = [
    path('', homePageView, name='home'),
    path('contato/', contactPageView, name='contact'),
]

simplemooc/simplemooc/courses/urls.py
from django.urls import path
from simplemooc.courses.views import coursePageView, detailsPageView, enrollmentPageView

urlpatterns = [
    path('', coursePageView, name='index'),
    path('<slug:slug>/', detailsPageView, name='details'),
    path('<slug:slug>/inscricao/', enrollmentPageView, name='enrollment'),
]

simplemooc/simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('simplemooc.core.urls', 'core'), namespace='core')),
    path('cursos/', include(('simplemooc.courses.urls', 'courses'), namespace='courses')),
    path('conta/', include(('simplemooc.accounts.urls', 'accounts'), namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/simplemooc/courses/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.

class CourseManager(models.Manager):
    
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | models.Q(description__icontains=query)    
        )

class Course(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição Simples', blank=True)
    about = models.TextField('Sobre o Curso', blank=True)
    start_date =  models.DateField('Data de Início', null=True, blank=True)
    image = models.ImageField(upload_to='courses/images', verbose_name='Imagem', null=True, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CourseManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courses:details", kwargs={"slug": self.slug})
    
    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']

class Enrollment(models.Model):

    STATUS_CHOICES = ((0, 'pendente'), (1, 'aprovado'), (2, 'cancelado'),)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', related_name='enrollments', on_delete=models.CASCADE)
    course = models.ForeignKey(Course, verbose_name='Curso', related_name='enrollments', on_delete=models.CASCADE)
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=0, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def active(self):
        self.status = 1
        self.save()

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user', 'course'),)

simplemooc/simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from simplemooc.core.mail import send_mail_template

class ContactCourse(forms.Form):
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    mensagem = forms.CharField(label='Mensagem/Dúvidas', widget=forms.Textarea)

    def send_email(self, course):
        subject = '[%s] Contato' % course
        
        context = {'name': self.cleaned_data['name'], 'email': self.cleaned_data['email'], 'message': self.cleaned_data['mensagem']}
        
        template_name = 'courses/contact_email.html'

        send_mail_template(subject, template_name, context, [settings.CONTACT_EMAIL])

simplemooc/simplemooc/courses/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Course, Enrollment
from .forms import ContactCourse

# Create your views here.

def coursePageView(request):
    courses = Course.objects.all()
    template_name = 'courses/index.html'
    context = {'courses': courses,}
    return render(request, template_name, context)

def detailsPageView(request, slug):
    course = get_object_or_404(Course, slug=slug)  #Course.objects.get(pk=pk)
    context = {}

    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_email(course)
            form = ContactCourse()
    else:
        form = ContactCourse()
    
    context['form'] = form
    context['course'] = course
    
    template_name = 'courses/details.html'
    return render(request, template_name, context)

@login_required
def enrollmentPageView(request, slug):
    course = get_object_or_404(Course, slug=slug)  #Course.objects.get(pk=pk)
    enrollment, created = Enrollment.objects.get_or_create(user=request.user, course = course)
    context = {}

    if created:
        enrollment.active()
        context['color'] = 'success'
        context['message'] = 'Incrição realizada com sucesso no curso "' + course.name + '" !'
        
    else:
        context['color'] ='red'
        context['message'] = 'Incrição já realizada neste curso!'

    return render(request, 'accounts/dashboard.html', context)
    

simplemooc/simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/simplemooc/courses/templates/courses/details.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}
<div class="ui secondary segment grey very padded">
    <div class="column">
      <p><h1 class="ui black header">{{ course }}</h1></p>
      <p>
        <h3 class="ui black header">{{ course.description }}</h3>  
      </p>
      <a class="ui primary button" href="{% url 'courses:enrollment' course.slug %}">
        Inscreva-se
      </a>
    </div>
</div>

<div class="ui segment very padded">
    <div class="ui stackable two column left align grid">
        <div class="twelve wide column">
            <h2 class="ui header"><u>Sobre o Curso</u></h2>
            <h5 class="">{{ course.about|linebreaks }}</h5>
        </div>
        <div class="four wide column">
                {% if course.image %}
                <img class='ui medium centered rounded image' src="{{ course.image.url }}" alt="{{ course.name }}" />
                {% else %}
                <img class='ui medium centered rounded image' src="{% static 'img/no-image.png' %}" alt="{{ course.name }}" />
                {% endif %}
                <h3 class='ui header'>Dúvidas?</h3>
                <button class="ui primary button" onclick="location.href='{% url 'core:contact' %}'">
                    Fale Conosco!
                </button>
        </div>
    </div>
    <div class="ui stackable two column left align grid" id="contato">
        <div class="six wide column">
            <h3 class="ui header">Tire suas dúvidas sobre o curso</h3>
            {% if is_valid %}
            <div class="ui success message">
                <i class="close icon"></i>
                <div class="header">
                    Sua dúvidas foram enviadas com sucesso!
                </div>
            </div>
            {% endif %}
            <form class='ui form' action="#contato" method='POST'>
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                    <div class="field">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                        <div class="ui red message">
                            <i class="close icon"></i>
                            <div class="">{{ field.errors }}</div>
                        </div>
                        {% endif %}
                    </div>  
                    {% endfor %}
                    <button class="ui button" type="submit">Submit</button>
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/simplemooc/courses/templates/courses/index.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}
<div class="ui secondary segment grey very padded">
    <div class="column">
      <p><h1 class="ui black header">Listagem de Cursos do SimpleMOOC</h1></p>
      <p>
        <h3 class="ui black header">Abaixo a lista de cursos disponíveis na plataforma.</h3>  
      </p>
    </div>
</div>

<div class="ui segment very padded">
    {% for course in courses %}
    <div class="ui container grey segment">
        <div class="ui stackable two column left align grid">
            <div class="four wide column">
                
                <a href="{{ course.get_absolute_url }}">
                {% if course.image %}
                <img class='ui medium centered rounded image' src="{{ course.image.url }}" alt="{{ course.name }}" />
                {% else %}
                <img class='ui medium centered rounded image' src="{% static 'img/no-image.png' %}" alt="{{ course.name }}" />
                {% endif %}
                </a>
                
            </div>
            <div class="twelve wide column">
                <h4 class="ui header"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
                {{ course.description|linebreaks }}
            </div>
        </div>
    </div>
    {% endfor %}
    {% if not courses %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <p>Nenhum curso está disponível na plataforma</p>
            </div>
        </div>
    </div>    
    {% endif %}
</div>
{% endblock %}