simplemooc/simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from simplemooc.accounts.views import registerPageView, dashboardPageView, editPageView, editPasswordPageView, passwordResetPageView, passwordResetConfirmPageView

urlpatterns = [
    path('', dashboardPageView, name='dashboard'),
    path('entrar/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('sair/', LogoutView.as_view(next_page = 'accounts:login'), name='logout'),
    path('cadastrar/', registerPageView, name='register'),
    path('esqueceu_senha/', passwordResetPageView, name='password_reset'),
    path('alterar_senha/<str:key>', passwordResetConfirmPageView, name='password_reset_confirm'),
    path('editar/', editPageView, name='edit'),
    path('editar_senha/', editPasswordPageView, name='edit_password'),
]

simplemooc/simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('simplemooc.core.urls', 'core'), namespace='core')),
    path('cursos/', include(('simplemooc.courses.urls', 'courses'), namespace='courses')),
    path('conta/', include(('simplemooc.accounts.urls', 'accounts'), namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/simplemooc/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

from django.conf import settings

# Create your models here.

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField("Nome de Usuário", max_length=30, unique=True, validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'), 'Nome de usuário inválido. Só serão permitidos caracteres alfanuméricos e (@, ., +, -, _, )', 'invalid')])
    email = models.EmailField("E-mail", unique=True)
    name = models.CharField("Nome", blank=True, max_length=50)
    is_active = models.BooleanField("Está ativo?", blank=True, default=True)
    is_staff = models.BooleanField("É da equipe?", blank=True, default=False)
    date_joined = models.DateTimeField("Data de entrada", auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    
    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', related_name='resets', on_delete=models.CASCADE)
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas senhas'
        ordering = ['-created_at']

simplemooc/simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import PasswordInput

from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generated_hash_key

from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        else:
            raise forms.ValidationError('Nenhum usuário encontrado com este e-mails')

    def save(self):
        user = User.objects.get(email = self.cleaned_data['email'])
        key = generated_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_email.html'

        #mail
        subject = 'Criar nova senha do SimpleMOOC!'
        context = {'reset': reset,}
        send_mail_template(subject, template_name, context, [user.email])

class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label='E-mail')
    password1 = forms.CharField(label = 'Senha', widget=PasswordInput)
    password2 = forms.CharField(label = 'Confirme sua senha', widget=PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('As senhas são diferentes')

        return password2

    def save(self, commit: True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()

        return user
    
    class Meta:
        model = User
        fields = ['username', 'email']

class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

simplemooc/simplemooc/accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

from simplemooc.courses.models import Enrollment
User = get_user_model()

# Create your views here.

@login_required
def dashboardPageView(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    context['enrollments'] = Enrollment.objects.filter(user = request.user).order_by('course')

    return render(request, template_name, context)

def registerPageView(request):
    template_name = 'accounts/register.html'
    context = {}

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            context['success'] = True
    else:
        form = RegisterForm()

    context['form'] = form
    return render(request, template_name, context)

def passwordResetPageView(request):
    template_name = 'accounts/password_reset.html'
    form = PasswordResetForm(request.POST or None)
    context = {}

    if form.is_valid():
        form.save()
        context['success'] = True

    context['form'] =  form

    return render(request, template_name, context)

def passwordResetConfirmPageView(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key = key)
    form = SetPasswordForm(user=reset.user, data = request.POST or None)

    if form.is_valid():
        form.save()
        context['success'] = True

    context['form'] = form
    return render(request, template_name, context)

@login_required
def editPageView(request):
    template_name = 'accounts/edit.html'
    form = EditAccountForm()
    context = {}

    if request.method == "POST":
        form = EditAccountForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            context['color'] = 'success'
            context['message'] = 'Os dados foram alterados com sucesso!'
            return render(request, 'accounts/dashboard.html', context)
    else:
        form = EditAccountForm(instance=request.user)

    context['form'] = form
    return render(request, template_name, context)

@login_required
def editPasswordPageView(request):
    template_name = 'accounts/edit_password.html'
    context = {}

    form = PasswordChangeForm(data = request.POST or None, user = request.user)
    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user) #Permanece logado apos alterar a senha
        context['color'] = 'success'
        context['message'] = 'A senha foi alterada com sucesso!'
        return render(request, 'accounts/dashboard.html', context)

    context['form'] = form
    return render(request, template_name, context)
    
         

simplemooc/simplemooc/accounts/templates/accounts/dashboard.html
{% extends 'partials/base.html' %}

{% load courses_tags %}

{% block content %}
<br>

<div class="ui segment very padded">
        {% if color %}
        <div class="ui {{color}} message">
            <i class="close icon"></i>
            <div class="header">
                {{ message }}
            </div>
        </div>
        {% endif %}
    <div class="ui stackable grid">
        <div class="column row">
            <div class="ui breadcrumb" style='padding-left: 15px;'>
                {% block breadcrumb_content %}
                <a class="section" href="{% url 'accounts:dashboard' %}">Meu painel</a>
                {% endblock breadcrumb_content %}
            </div>
        </div>
        <div class="four wide column">
            <div class="ui vertical accordion fluid menu">
                <div class="item">
                    <a class="title">
                        <i class="dropdown icon"></i>
                        Meus cursos
                    </a>
                    <div class="content">
                        {% load_my_courses user as enrollments%}  
                        {% for enrollment in enrollments %}
                        <div>
                            <a class="item">
                                {{ enrollment.course }}
                            </a>
                        </div>
                        {% empty %}
                        <div class='item'>
                            Nenhum curso disponível
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="item">
                    <a class="title">
                        <i class="dropdown icon"></i>
                        Configurações da conta
                    </a>
                    <div class="{% if request.resolver_match.url_name == 'edit' or request.resolver_match.url_name == 'edit_password' %}active{% endif %} content">
                        <div>
                            <a class="item" href="{% url 'accounts:edit' %}">
                                Editar informações
                            </a>
                        </div>
                        <div>
                            <a class="item" href="{% url 'accounts:edit_password' %}">
                                Editar senha
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="twelve wide column">
            <div class="ui segment dashboard transition hidden">
                {% block dashboard_content %}
                <h5 class="header">Seja bem-vindo, {{ user }}!</h5>
                {% endblock dashboard_content %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

simplemooc/simplemooc/accounts/templates/accounts/edit.html
{% extends 'accounts/dashboard.html' %}

{% block breadcrumb_content %}
    {{ block.super }}
    <i class="right chevron icon divider"></i>
    <a class="section" href="{% url 'accounts:edit' %}">Editar conta</a>
{% endblock breadcrumb_content %}

{% block dashboard_content %}
    <form class="ui form" action="#edit" method='POST'>
        {% csrf_token %}
        {% for field in form %}
        <div class="field">
            {{ field.label_tag}}
            <div class="ui left icon input">
                {{ field }}
                {% if field.name == 'username' %}<i class="user icon"></i>
                {% elif field.name == 'email' %}<i class="envelope icon"></i>
                {% else %}<i class="user id card icon"></i>
                {% endif %}
            </div>
            
            {% if field.errors %}
            <div class="ui red message">
                <i class="close icon"></i>
                <div class="">{{ field.errors }}</div>
            </div>
            {% endif %}
        </div>
        {% endfor %}
        <div class="center aligned">
            <div class="ui form">
                <button type="submit" class="ui blue right labeled icon button"><i class="signup icon"></i>Salvar modificações</button>
            </div>
        </div>
    </form>

{% endblock dashboard_content %}

simplemooc/simplemooc/accounts/templates/accounts/edit_password.html
{% extends 'accounts/dashboard.html' %}

{% block breadcrumb_content %}
    {{ block.super }}
    <i class="right chevron icon divider"></i>
    <a class="section" href="{% url 'accounts:edit_password' %}">Editar senha</a>
{% endblock breadcrumb_content %}

{% block dashboard_content %}
    {% if success %}
    <div class="ui success message">
        <i class="close icon"></i>
        <div class="header">
            A senha foi alterada com sucesso!
        </div>
    </div>
    {% endif %}

    <form class="ui form" action="#edit" method='POST'>
        {% csrf_token %}
        {% for field in form %}
        <div class="field">
            {{ field.label_tag}}
            <div class="ui left icon input">
                {{ field }}
                {% if field.name == 'old_password' %}<i class="unlock alternate icon"></i>
                {% else %}<i class="key icon"></i>
                {% endif %}
            </div>
            
            {% if field.errors %}
            <div class="ui red message">
                <i class="close icon"></i>
                <div class="">{{ field.errors }}</div>
            </div>
            {% endif %}
        </div>
        {% endfor %}
        <div class="center aligned">
            <div class="ui form">
                <button type="submit" class="ui blue right labeled icon button"><i class="signup icon"></i>Salvar modificações</button>
            </div>
        </div>
    </form>

{% endblock dashboard_content %}

simplemooc/simplemooc/accounts/templates/accounts/login.html
{% extends 'partials/base.html' %}

{% block content %}
<br>
<div class="ui segment very padded">
    <div class="ui centered column stackable grid container">
        {% if form.username.value != None %}
        <div class="ui red message">
            <i class="close icon"></i>
            {{ form.non_field_errors.as_text }}
        </div>
        {% endif %}
        <div class="eight wide column">
            <div class='ui fluid card login transition hidden'>
                <div class="content">
                    <div class='center aligned'>
                        <h2>Login</h2>
                    </div>
                </div>
        
                <div class="content">
                    <form class="ui form" action="#login" method='POST'>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="field">
                            {{ field.label_tag}}
                            <div class="ui left icon input">
                                {{ field }}
                                {% if field.name == 'username'%}<i class="user icon"></i>
                                {% elif field.name == 'password'%}<i class="key icon"></i>
                                {% endif %}
                                {% if field.errors %}
                                <div class="ui red message">
                                    <i class="close icon"></i>
                                    <div class="">{{ field.errors }}</div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                        <div class="center aligned">
                            <div class="ui form">
                                <button type="submit" class="ui blue right labeled icon button"><i class="sign-in icon"></i>Entrar</button>
                                <a class="ui yellow right labeled icon button" href="{% url 'accounts:password_reset' %}"><i class="undo icon"></i>Esqueceu a senha?</a>
                                <a class="ui red right labeled icon button" href="{% url 'accounts:register' %}"><i class="signup icon"></i>Cadastrar-se</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

simplemooc/simplemooc/accounts/templates/accounts/password_reset.html
{% extends 'partials/base.html' %}

{% block content %}

<br>
<div class="ui segment very padded">
    <div class="ui centered column stackable grid container">
        <div class="eight wide column">
            <div class='ui fluid card login transition hidden'>
                {% if success %}
                <div class="content">
                    <div class="ui success message">
                        <i class="close icon"></i>
                        <div class="header">
                            Cheque sua caixa de e-mail para alterar a senha!
                        </div>
                    </div>
                </div>
                <meta http-equiv="refresh" content="3;url={% url 'accounts:login' %}"> 
                {% else %}
                <div class="content">
                    <div class='center aligned'>
                        <h2>Informe seu e-mail:</h2>
                    </div>
                </div>
                
                <div class="content">
                    <form class="ui form" action="#forget" method='POST'>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="field">
                            {{ field.label_tag}}
                            <div class="ui left icon input">
                                {{ field }}
                                <i class="envelope icon"></i>
                            </div>
                            
                            {% if field.errors %}
                            <div class="ui red message">
                                <i class="close icon"></i>
                                <div class="">{{ field.errors }}</div>
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <div class="center aligned">
                            <div class="ui form">
                                <button type="submit" class="ui blue right labeled icon button"><i class="paper plane icon"></i>Enviar email</button>
                            </div>
                        </div>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

simplemooc/simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends 'partials/base.html' %}

{% block content %}

<br>
<div class="ui segment very padded">
    <div class="ui centered column stackable grid container">
        <div class="eight wide column">
            <div class='ui fluid card login transition hidden'>
                {% if success %}
                <div class="content">
                    <div class="ui success message">
                        <i class="close icon"></i>
                        <div class="header">
                            Sua senha foi alterada com sucesso!
                        </div>
                    </div>
                </div>
                <meta http-equiv="refresh" content="3;url={% url 'accounts:login' %}"> 
                {% else %}
                <div class="content">
                    <div class='center aligned'>
                        <h2>Informe sua nova senha:</h2>
                    </div>
                </div>
                
                <div class="content">
                    <form class="ui form" action="#forget" method='POST'>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="field">
                            {{ field.label_tag}}
                            <div class="ui left icon input">
                                {{ field }}
                                <i class="key icon"></i>
                            </div>
                            
                            {% if field.errors %}
                            <div class="ui red message">
                                <i class="close icon"></i>
                                <div class="">{{ field.errors }}</div>
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <div class="center aligned">
                            <div class="ui form">
                                <button type="submit" class="ui blue right labeled icon button"><i class="edit icon"></i>Alterar senha</button>
                            </div>
                        </div>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

simplemooc/simplemooc/accounts/templates/accounts/password_reset_email.html
<!-- Corpo do email para resetar a senha -->
<p>Para criar uma nova senha, acesse o link:<a href="http://10.0.0.19:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="">link</a></p>

simplemooc/simplemooc/accounts/templates/accounts/register.html
{% extends 'partials/base.html' %}

{% block content %}
<br>
<div class="ui segment very padded">
    <div class="ui centered column stackable grid container">
        <div class="eight wide column">
            <div class='ui fluid card login transition hidden'>
                <div class="content">
                    <div class='center aligned'>
                        <h2>Cadastre-se</h2>
                    </div>
                </div>
        
                <div class="content">
                    {% if success %}
                    <div class="ui success message">
                        <i class="close icon"></i>
                        <div class="header">
                            O usuário foi criado com sucesso!
                        </div>
                    </div>
                    <meta http-equiv="refresh" content="3;url={% url 'accounts:login' %}"> 
                    {% endif %}
                    <form class="ui form" action="#register" method='POST'>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="field">
                            {{ field.label_tag}}
                            <div class="ui left icon input">
                                {{ field }}
                                {% if field.name == 'username' %}<i class="user icon"></i>
                                {% elif field.name == 'email' %}<i class="envelope icon"></i>
                                {% else %}<i class="key icon"></i>
                                {% endif %}
                            </div>
                            
                            {% if field.errors %}
                            <div class="ui red message">
                                <i class="close icon"></i>
                                <div class="">{{ field.errors }}</div>
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <div class="center aligned">
                            <div class="ui form">
                                <button type="submit" class="ui blue right labeled icon button"><i class="signup icon"></i>Cadastrar-se</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}